use std::env;
use std::path::PathBuf;
use std::fs;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let gna_root = manifest_dir.join("gna").join("src");
    let header = gna_root.join("gna-api").join("gna2-api.h");

    if !header.exists() {
        panic!("GNA API header not found at {}", header.display());
    }

    println!("cargo:rerun-if-changed={} ", header.display());
    println!("cargo:rerun-if-changed={} ", gna_root.display());

    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .clang_arg(format!("-I{}", gna_root.display()))
        .clang_arg("-xc++")
        .clang_arg("-std=c++17")
        .derive_default(true)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("Unable to generate GNA bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let mut code = bindings.to_string();
    // Rust 2024 edition requires extern blocks to be marked unsafe explicitly.
    // Force all extern blocks generated by bindgen to be marked unsafe.
    code = code.replace("extern \"C\" {", "unsafe extern \"C\" {");

    fs::write(out_path.join("gna_bindings.rs"), code)
        .expect("Couldn't write GNA bindings");
}
