use std::env;
use std::path::PathBuf;
use std::fs;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let gna_root = manifest_dir.join("gna").join("src");
    let header = gna_root.join("gna-api").join("gna2-api.h");

    if !header.exists() {
        panic!("GNA API header not found at {}", header.display());
    }

    println!("cargo:rerun-if-changed={} ", header.display());
    println!("cargo:rerun-if-changed={} ", gna_root.display());

    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .clang_arg(format!("-I{}", gna_root.display()))
        .clang_arg("-xc++")
        .clang_arg("-std=c++17")
        .derive_default(true)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("Unable to generate GNA bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let mut code = bindings.to_string();
    // Rust 2024 edition requires extern blocks to be marked unsafe explicitly.
    // Force all extern blocks generated by bindgen to be marked unsafe.
    code = code.replace("extern \"C\" {", "unsafe extern \"C\" {");
    // bindgen sometimes already emits `unsafe extern "C" {` causing the previous
    // replace to produce `unsafe unsafe extern "C" {`. Fix that case as well.
    code = code.replace("unsafe unsafe extern \"C\"", "unsafe extern \"C\"");

    fs::write(out_path.join("gna_bindings.rs"), code)
        .expect("Couldn't write GNA bindings");

    // If user enabled the `link_gna` feature, add linker flags automatically.
    // Expects either environment variable `GNA_LIB_DIR` pointing to the folder
    // containing the GNA shared library (e.g., gna.dll or libgna.so), or tries
    // a couple of sensible repo-local locations.
    if env::var("CARGO_FEATURE_LINK_GNA").is_ok() {
        // Prefer explicit environment variable
        let lib_dir = env::var("GNA_LIB_DIR").ok().or_else(|| {
            let candidates = [
                gna_root.join("bin"),
                manifest_dir.join("gna").join("bin"),
                manifest_dir.join("gna").join("build"),
            ];
            for c in &candidates {
                if c.exists() {
                    return Some(c.to_string_lossy().to_string());
                }
            }
            None
        });

        let lib_dir = match lib_dir {
            Some(d) => d,
            None => panic!("feature 'link_gna' enabled but GNA library directory not found. Set GNA_LIB_DIR to the folder containing gna.dll / libgna.so"),
        };

        println!("cargo:rustc-link-search=native={}", lib_dir);
        // Link dynamic library named `gna` (gna.dll on Windows, libgna.so on Linux)
        println!("cargo:rustc-link-lib=dylib=gna");
    }
}
